# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    allow_integration_in_goal_trajectories: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint5
    command_interfaces:
      - velocity
    state_interfaces:
      - position 
      - velocity

    gains:

      joint1: {p: 10.0, d: 0.5, i: 2.0, i_clamp: 1.0}
      joint2: {p: 10.0, d: 0.5, i: 2.0, i_clamp: 1.0}
      joint3: {p: 10.0, d: 0.5, i: 2.0, i_clamp: 1.0}
      joint5: {p: 10.0, d: 0.5, i: 2.0, i_clamp: 1.0}