<?xml version="1.0"?>
<?xml-model href="https://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>scrb_common_util</name>
    <version>0.0.0</version>
    <description>Common Utilities</description>
    <maintainer email="will.free@spaceconcordia.ca">Will Free</maintainer>
    <license>MIT</license>

    <depend>rclcpp</depend>
    <depend>ros2_fmt_logger</depend>
    <depend>tf2_eigen</depend>
    <depend>tf2_geometry_msgs</depend>

    <build_depend>backward_ros</build_depend>
    <build_depend>scrb_cmake_utils</build_depend>

    <buildtool_depend>ament_cmake_ros</buildtool_depend>

    <test_depend>ament_cmake_gtest</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
