#!/bin/bash

gst-launch-1.0 rtspsrc location=rtsp://10.240.0.10:8554/RGB buffer-mode=auto latency=0 ! \
               rtpssrcdemux ! rtph264depay ! \
               h264parse ! avdec_h264 ! \
               videoflip method=none ! gamma gamma=1.0 ! \
               queue ! videoconvert ! autovideosink >/dev/null 2>&1 &

gst-launch-1.0 rtspsrc location=rtsp://10.240.0.10:8445/front buffer-mode=auto latency=0 ! \
               rtpssrcdemux ! rtph264depay ! \
               h264parse ! avdec_h264 ! \
               videoflip method=counterclockwise ! gamma gamma=0.5 ! \
               queue ! videoconvert ! autovideosink >/dev/null 2>&1 &

gst-launch-1.0 rtspsrc location=rtsp://10.240.0.10:8445/left buffer-mode=auto latency=0 ! \
               rtpssrcdemux ! rtph264depay ! \
               h264parse ! avdec_h264 ! \
               videoflip method=none ! gamma gamma=0.5 ! \
               queue ! videoconvert ! autovideosink >/dev/null 2>&1 &

gst-launch-1.0 rtspsrc location=rtsp://10.240.0.10:8445/right buffer-mode=auto latency=0 ! \
               rtpssrcdemux ! rtph264depay ! \
               h264parse ! avdec_h264 ! \
               videoflip method=none ! gamma gamma=0.5 ! \
               queue ! videoconvert ! autovideosink >/dev/null 2>&1 &
