<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>foc2_gui</name>
    <version>0.0.0</version>
    <description>Forward Operating C2 GUI</description>
    <maintainer email="will.free@spaceconcordia.ca">Will Free</maintainer>
    <license>MIT</license>

    <depend>rclcpp</depend>
    <depend>rclcpp_components</depend>
    <depend>rclcpp_action</depend>

    <depend>geometry_msgs</depend>
    <depend>nav2_msgs</depend>
    <depend>action_msgs</depend>
    <depend>lifecycle_msgs</depend>
    <depend>ros_aruco_opencv_msgs</depend>
    <depend>rover_msgs</depend>

    <depend>tf2_ros</depend>
    <depend>image_transport</depend>
    <depend>ros2_fmt_logger</depend>
    <depend>scrb_common_util</depend>

    <depend>gstreamer1.0</depend>
    <depend>gstreamer1.0-rtsp</depend>
    <depend>geographiclib</depend>
    <depend>libopencv-dev</depend>
    <depend>opengl</depend>
    <depend>freetype</depend>
    <depend>libx11-dev</depend>
    <depend>libx11-xcb-dev</depend>
    <depend>libxtst-dev</depend>

    <build_depend>libgstreamer1.0-dev</build_depend>
    <build_depend>libgstrtspserver-1.0-dev</build_depend>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>robot_localization</exec_depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
