# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.1.5 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  base_pivot_shoulder_gearbox_joint:
    has_velocity_limits: false
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  base_structure_joint:
    has_velocity_limits: false
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  bicep_tube_gearbox_joint:
    has_velocity_limits: false
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  forearm_tube_wrist_gearbox_joint:
    has_velocity_limits: false
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_claw_joint:
    has_velocity_limits: false
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0