# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ceres_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ceres_arm_controller:
  ros__parameters:
    joints:
      - base_structure_joint
      - base_pivot_shoulder_gearbox_joint
      - bicep_tube_gearbox_joint
      - forearm_tube_wrist_gearbox_joint
      - gripper_claw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity