controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    command_interfaces:
      - velocity

    left_wheel_names: [ "front_left_bogey_forwards_bar_to_wheel", "front_left_bogey_backwards_bar_to_wheel", "back_bogey_left_leg_to_wheel" ]
    right_wheel_names: [ "front_right_bogey_forwards_bar_to_wheel", "front_right_bogey_backwards_bar_to_wheel", "back_bogey_right_leg_to_wheel" ]

    wheel_separation: 1.25
    wheels_per_side: 3
    wheel_radius: 0.3

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [ 0.001, 0.0, 0.0, 0.0, 0.0, 0.01 ]
    twist_covariance_diagonal: [ 0.001, 0.0, 0.0, 0.0, 0.0, 0.01 ]

    open_loop: true
    enable_odom_tf: true

    use_stamped_vel: false

    cmd_vel_timeout: 0.5

    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        max_jerk: 0.0
        min_jerk: 0.0

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
        max_jerk: 0.0
        min_jerk: 0.0
