name: Build & Lint

on:
  pull_request:
    branches: [ main, master, develop ]
    paths: [ '**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake' ]

  push:
    branches: [ main, master, develop ]
    paths: [ '**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake' ]

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    environment: approval

    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Setup environment
        shell: bash
        run: |
          vcs import external < external.repos

          # install dependencies
          rosdep update
          rosdep install -r -y --rosdistro jazzy --ignore-src --from-paths $(colcon list --paths-only)

          # set up compiler
          apt -y install software-properties-common
          # install the llvm & clang 22
          wget 'https://apt.llvm.org/llvm.sh'
          chmod +x ./llvm.sh
          ./llvm.sh 22 # probably not the best, buuutttt it's llvm, so whatever
          apt -y install clang-tidy-22 clang-format-22
          add-apt-repository -y ppa:ubuntu-toolchain-r/test
          apt -y install gcc-16 libstdc++-16-dev

          # update alternatives (we're not building with gcc, so don't bother updating it)
          for bin in clang clang++ clang-{format,tidy} lld; do
            if `echo "$bin" | grep -qi '[0-9]'`; then
              continue
            fi
            update-alternatives --install "/usr/bin/$bin" "$bin" "/usr/bin/$bin"-22 100
          done

          # setup ROS
          source /opt/ros/jazzy/setup.bash
          colcon mixin add default 'https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml'
          colcon mixin update default

      - name: Cache build
        uses: actions/cache@v6
        with:
          path: build
          key: colcon-build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            colcon-build-${{ runner.os }}-

      - name: Build packages
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash

          # note: this must be built in release mode, otherwise it fails (thanks peel & glib)
          colcon build --mixin lld compile-commands ninja clang release


      - name: Run linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use .clang-format config file.
          tidy-checks: '' # Use .clang-tidy config file.
          # only 'update' a single comment in a pull request's thread.
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          step-summary: true
          database: 'build/'
          tidy-review: true
          format-review: true
